{{- if empty .Values.secrets }}
{{- fail "secrets is required" }}
{{- end }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ required "name is required" .Values.name }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
spec:
  refreshPolicy: {{ .Values.refreshPolicy | default "OnChange" }}
  refreshInterval: {{ .Values.refreshInterval | default "0" | quote }}
  secretStoreRef:
    name: {{ required "secretStoreName is required" .Values.secretStoreName }}
    kind: SecretStore
  target:
    name: {{ required "targetName is required" .Values.targetName }}
  data:
    {{- range .Values.secrets }}
    - secretKey: {{ . | replace "/" "_" | trimPrefix "_" | quote }}
      remoteRef:
        key: {{ . | quote }}
    {{- end }}
