{{- if empty .Values.provider }}
{{- fail "provider is required" }}
{{- end }}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ required "secretStoreName is required" .Values.secretStoreName }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
spec:
  provider:
    {{- toYaml .Values.provider | nindent 4 }}
