apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  revisionHistoryLimit: 1
  replicas: {{ .Values.deployment.replicas }}
  {{- if .Values.deployment.volumes }}
  # ReadWriteOnce volumes can't be shared by old and new pods during a rolling update.
  strategy:
    type: Recreate
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      {{- with .Values.deployment.ips }}
      imagePullSecrets:
        - name: {{ . }}
      {{- end }}
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.deployment.container.package }}:{{ .Values.deployment.container.tag }}
          imagePullPolicy: IfNotPresent
          env:
            {{- range .Values.deployment.env }}
            - name: {{ .name }}
              {{- if .value }}
              value: {{ .value | quote }}
              {{- else if .secret }}
              valueFrom:
                secretKeyRef:
                  name: {{ .secret.store }}
                  key: {{ .secret.key }}
              {{- end }}
            {{- end }}
          {{- with .Values.deployment.volumes }}
          volumeMounts:
            {{- range . }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
            {{- end }}
          {{- end }}
      {{- with .Values.deployment.volumes }}
      volumes:
        {{- range . }}
        - name: {{ .name }}
          persistentVolumeClaim:
            claimName: {{ $.Values.name }}-{{ .name }}
        {{- end }}
      {{- end }}
