name: Publish external-secret

on:
  push:
    branches:
      - main
    paths:
      - charts/external-secret/**

jobs:
  publish:
    uses: ./.github/workflows/publish-chart.yaml
    with:
      chart_name: external-secret
      chart_path: charts/external-secret
    permissions:
      contents: read
      packages: write
