name: Publish application

on:
  push:
    branches:
      - main
    paths:
      - charts/application/**

jobs:
  publish:
    uses: ./.github/workflows/publish-chart.yaml
    with:
      chart_name: application
      chart_path: charts/application
    permissions:
      contents: read
      packages: write
